apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: goslack

resources:
  - namespace.yaml
  - secret.yaml
  - configmap.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - migration-job.yaml
  - goslack-api-deployment.yaml
  - goslack-api-service.yaml
  - ingress.yaml

# Common labels applied to all resources
commonLabels:
  project: goslack
  version: v1.0.0

# Images to be updated (useful for CI/CD)
images:
  - name: goslack-api
    newTag: latest

