apiVersion: v1
kind: Secret
metadata:
  name: goslack-secrets
  namespace: goslack
type: Opaque
data:
  # Base64 encoded values
  # postgres-password: secret (c2VjcmV0)
  # jwt-secret-key: 12345678901234567890123456789012 (MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=)
  postgres-password: c2VjcmV0
  jwt-secret-key: MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: goslack
type: Opaque
data:
  # Base64 encoded values
  # postgres-user: root (cm9vdA==)
  # postgres-password: secret (c2VjcmV0)
  # postgres-db: goslack (Z29zbGFjaw==)
  postgres-user: cm9vdA==
  postgres-password: c2VjcmV0
  postgres-db: Z29zbGFjaw==

